steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['package']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/fx-fussballtipp-wicket/$REPO_NAME:$REVISION_ID', '.']
images: ['gcr.io/fx-fussballtipp-wicket/$REPO_NAME:$REVISION_ID']